In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve() / "code"))

from clinical_ts.utils.ecg_utils import *
from clinical_ts.data.time_series_dataset_utils import *

In [2]:
DATASET_DIR = Path("/home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data")
TARGET_DIR = Path("processed")

In [3]:
CHANNEL_ITOS = "canonical"
channel_stoi_canonical = {"i": 0, "ii": 1, "iii":2, "avr":3, "avl":4, "avf":5, "v1":6, "v2":7, "v3":8, "v4":9, "v5":10, "v6":11, "vx":12, "vy":13, "vz":14}

# PTB

In [5]:
ptb_data_path_root = DATASET_DIR / "ptb"
ptb_target_folder_root = TARGET_DIR / "ptb"

In [ ]:
df_ptb, _, _, _ = prepare_ptbv2(
    data_path=ptb_data_path_root,
    target_folder=ptb_target_folder_root
)

In [ ]:
reformat_as_memmap(
    df=df_ptb,
    target_filename=Path(ptb_target_folder_root)/"memmap.npy",
    fs=1000,
    channel_itos=CHANNEL_ITOS,
    data_folder=ptb_target_folder_root
)

  0%|          | 0/549 [00:00<?, ?it/s]

,filename,data,patient_id,age,sex,ECG date,Reason for admission,Acute infarction (localization),Former infarction (localization),Additional diagnoses,...,acute_MI,catheterized,MI,MI_status,label,strat_fold,data_mean,data_std,data_length,data_original
0,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,0,1,81,female,1990-10-17,Myocardial infarction,infero-latera,no,[ Diabetes mellitus],...,False,True,True,old,"[0, 5]",1,"[0.0002162977, -0.00020319605, 0.000100099394,...","[0.23092301, 0.94018084, 0.99643004, 0.4694975...",115200,s0014lre.npy
1,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,1,1,81,female,1990-10-18,Myocardial infarction,infero-latera,no,[ Diabetes mellitus],...,False,True,True,old,"[0, 5]",1,"[-0.00021352063, 0.00019857484, -0.00012690101...","[0.22376014, 0.36905, 0.38887003, 0.23512886, ...",115200,s0016lre.npy
2,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,2,1,81,female,1990-10-01,Myocardial infarction,infero-latera,no,[ Diabetes mellitus],...,True,True,True,acute catheterized,"[3, 5]",1,"[-0.00010852692, -0.00021298771, 8.8704895e-05...","[0.15624636, 0.20232826, 0.2158746, 0.1451186,...",38400,s0010_re.npy
3,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,3,2,58,female,1990-10-17,Myocardial infarction,anterior,no,"[ Arterial hypertension, Adiposis hepatis, G...",...,False,True,True,old,"[0, 1]",4,"[0.0001163011, -0.00019013508, 0.0001947446, 3...","[0.40440923, 1.5066507, 1.1559782, 0.93951994,...",115200,s0015lre.npy
4,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,4,3,63,male,1990-10-18,Myocardial infarction,infero-postero-lateral,no,[ no],...,False,True,True,old,[0],0,"[0.00015871543, -0.00011346146, 0.0003265667, ...","[0.23876877, 0.2979724, 0.16587229, 0.2569257,...",115200,s0017lre.npy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,544,292,66,male,1997-06-03,Myocardial infarction,antero-lateral,no,[ Arterial hypertension],...,False,False,True,old,"[0, 1]",1,"[0.0001655581, -0.00025652762, 0.00072179636, ...","[0.7290855, 1.8932093, 2.2646847, 0.879821, 1....",120012,s0555_re.npy
545,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,545,292,66,male,1997-06-03,Myocardial infarction,antero-lateral,no,[ Arterial hypertension],...,False,False,True,old,"[0, 1]",1,"[2.9081937e-05, -0.00016307946, 0.00023617566,...","[0.3047532, 1.213483, 1.2753047, 0.61319166, 0...",120012,s0556_re.npy
546,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,546,293,75,male,1997-06-03,Myocardial infarction,antero-lateral,no,[ unknown],...,False,False,True,old,[0],4,"[-4.3589414e-05, -0.0002437092, -0.0004955694,...","[0.71931934, 0.6753292, 0.3853054, 0.67052794,...",120012,s0557_re.npy
547,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,547,293,75,male,1997-06-03,Myocardial infarction,antero-lateral,no,[ unknown],...,False,False,True,old,[0],4,"[0.00010396327, -0.00026168278, 0.00015408709,...","[0.33328155, 0.1724379, 0.19920357, 0.24592867...",120012,s0558_re.npy
548,/home/nvelingker/mkeoliya/kardia-lm/src/pipeli...,548,294,61,female,1997-06-05,Myocardial infarction,inferior,no,[ unknown],...,False,False,True,old,[0],1,"[0.00017927449, 5.0509996e-05, -0.00011328485,...","[1.0195022, 2.408848, 3.3984683, 0.73047864, 2...",120012,s0559_re.npy

# CPSC 2018

In [ ]:
cpsc2018_data_path_root = DATASET_DIR / "cpsc2018"
cpsc2018_target_folder_root = TARGET_DIR / "cpsc2018"

In [ ]:
df_cpsc2018, _, _, _ = prepare_data_cpsc2018(
    data_path=cpsc2018_data_path_root,
    target_folder=cpsc2018_target_folder_root
)

  0%|          | 0/6877 [00:00<?, ?it/s]

Creating CV folds: cpsc2018

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/220 [00:00<?, ?it/s]

  0%|          | 0/232 [00:00<?, ?it/s]

  0%|          | 0/601 [00:00<?, ?it/s]

  0%|          | 0/689 [00:00<?, ?it/s]

  0%|          | 0/702 [00:00<?, ?it/s]

  0%|          | 0/834 [00:00<?, ?it/s]

  0%|          | 0/918 [00:00<?, ?it/s]

  0%|          | 0/1148 [00:00<?, ?it/s]

  0%|          | 0/1533 [00:00<?, ?it/s]

In [ ]:
reformat_as_memmap(
    df=df_cpsc2018,
    target_filename=Path(cpsc2018_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=cpsc2018_target_folder_root
)

  0%|          | 0/6877 [00:00<?, ?it/s]

,data,label,sex,age,dataset,label_filtered,label_filtered_numeric,label_numeric,strat_fold,data_mean,data_std,data_length,data_original
0,0,[right bundle branch block],male,74.0,cpsc2018,[right bundle branch block],[4],[4],2,"[-0.00022879851, 0.00027054705, 0.00049932965,...","[0.15633993, 0.17364642, 0.100332834, 0.157314...",7500,A0001.npy
1,1,[sinus rhythm],female,49.0,cpsc2018,[sinus rhythm],[5],[5],7,"[-2.0221808e-07, 4.39806e-06, -1.5995369e-06, ...","[0.064599745, 0.083601415, 0.04205446, 0.07168...",5000,A0002.npy
2,2,[atrial fibrillation],female,81.0,cpsc2018,[atrial fibrillation],[1],[1],4,"[1.279895e-05, 8.398238e-06, -5.798889e-06, -1...","[0.2192809, 0.16895786, 0.16063172, 0.17851427...",5000,A0003.npy
3,3,[atrial fibrillation],male,45.0,cpsc2018,[atrial fibrillation],[1],[1],3,"[7.026269e-06, 3.5180583e-06, 8.3682016e-07, -...","[0.21334991, 0.14936016, 0.10065729, 0.1771536...",5974,A0004.npy
4,4,[ventricular ectopics],male,53.0,cpsc2018,[ventricular ectopics],[8],[8],7,"[4.4796766e-06, 0.0003248, 0.00032031938, 0.00...","[0.050634287, 0.1899224, 0.16442887, 0.1118145...",12500,A0005.npy
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6872,6872,[1st degree av block],male,80.0,cpsc2018,[1st degree av block],[0],[0],0,"[0.00020757057, -0.0004025731, 0.00038985818, ...","[0.10476242, 0.0685412, 0.07189233, 0.08075753...",7000,A6873.npy
6873,6873,[st depression],female,62.0,cpsc2018,[st depression],[6],[6],5,"[-0.0004583712, 2.8649878e-05, 0.00048700528, ...","[0.08557823, 0.10870912, 0.06627183, 0.0919323...",8000,A6874.npy
6874,6874,[left bundle branch block],male,78.0,cpsc2018,[left bundle branch block],[2],[2],6,"[3.3922852e-06, -1.8510713e-06, -6.257207e-06,...","[0.1438753, 0.2931554, 0.23959965, 0.19740461,...",26531,A6875.npy
6875,6875,[atrial fibrillation],female,-1.0,cpsc2018,[atrial fibrillation],[1],[1],8,"[-0.0003552851, 0.00015870864, -0.0004860017, ...","[0.076872535, 0.05515438, 0.07487602, 0.055285...",7000,A6876.npy
6876,6876,[ventricular ectopics],female,71.0,cpsc2018,[ventricular ectopics],[8],[8],0,"[3.136543e-06, 8.6515956e-07, -4.546683e-06, -...","[0.1236198, 0.1178664, 0.059316844, 0.1170807,...",18488,A6877.npy

# CPSC-Extra

In [ ]:
cpsc_extra_data_path_root = DATASET_DIR / "cpsc_extra"
cpsc_extra_target_folder_root = TARGET_DIR / "cpsc_extra"

In [ ]:
df_cpsc_extra, _, _, _ = prepare_data_cpsc_extra(
    data_path=cpsc_extra_data_path_root,
    target_folder=cpsc_extra_target_folder_root
)

  0%|          | 0/3453 [00:00<?, ?it/s]

Creating CV folds: cpsc_extra

  0%|          | 0/72 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]

  0%|          | 0/31 [00:00<?, ?it/s]

  0%|          | 0/32 [00:00<?, ?it/s]

  0%|          | 0/34 [00:00<?, ?it/s]

  0%|          | 0/37 [00:00<?, ?it/s]

  0%|          | 0/36 [00:00<?, ?it/s]

  0%|          | 0/38 [00:00<?, ?it/s]

  0%|          | 0/44 [00:00<?, ?it/s]

  0%|          | 0/51 [00:00<?, ?it/s]

  0%|          | 0/54 [00:00<?, ?it/s]

  0%|          | 0/46 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

  0%|          | 0/64 [00:00<?, ?it/s]

  0%|          | 0/52 [00:00<?, ?it/s]

  0%|          | 0/79 [00:00<?, ?it/s]

  0%|          | 0/103 [00:00<?, ?it/s]

  0%|          | 0/108 [00:00<?, ?it/s]

  0%|          | 0/105 [00:00<?, ?it/s]

  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/162 [00:00<?, ?it/s]

  0%|          | 0/165 [00:00<?, ?it/s]

  0%|          | 0/191 [00:00<?, ?it/s]

  0%|          | 0/260 [00:00<?, ?it/s]

  0%|          | 0/294 [00:00<?, ?it/s]

  0%|          | 0/521 [00:00<?, ?it/s]

  0%|          | 0/545 [00:00<?, ?it/s]

In [ ]:
reformat_as_memmap(
    df=df_cpsc_extra,
    target_filename=Path(cpsc_extra_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=cpsc_extra_target_folder_root
)

  0%|          | 0/3453 [00:00<?, ?it/s]

,data,label,sex,age,dataset,label_filtered,label_filtered_numeric,label_numeric,strat_fold,data_mean,data_std,data_length,data_original
0,0,"[old myocardial infarction, sinus tachycardia]",male,53.0,cpsc_extra,"[old myocardial infarction, sinus tachycardia]","[19, 26]","[36, 53]",9,"[-2.8023676e-06, -1.7988624e-06, -4.0086545e-0...","[0.085400246, 0.085010685, 0.099571615, 0.0691...",5000,Q0001.npy
1,1,[myocardial ischemia],female,70.0,cpsc_extra,[myocardial ischemia],[17],[33],0,"[0.00037733227, 0.000110249886, -0.0002670547,...","[0.20751943, 0.1401629, 0.15901272, 0.15806608...",7500,Q0002.npy
2,2,"[old myocardial infarction, nonspecific st t a...",male,55.0,cpsc_extra,"[old myocardial infarction, nonspecific st t a...","[19, 18]","[36, 35]",6,"[0.00019650029, 0.00015549884, -4.099929e-05, ...","[0.073997594, 0.05868569, 0.098126225, 0.04510...",6000,Q0003.npy
3,3,"[myocardial ischemia, nonspecific st t abnorma...",male,57.0,cpsc_extra,"[myocardial ischemia, nonspecific st t abnorma...","[17, 18]","[33, 35]",7,"[1.200118e-06, -9.199081e-06, 1.3975432e-06, -...","[0.07156837, 0.12845865, 0.075529225, 0.096867...",5000,Q0004.npy
4,4,[nonspecific st t abnormality],female,51.0,cpsc_extra,[nonspecific st t abnormality],[18],[35],1,"[-1.6354157e-06, 7.6142743e-07, 1.2117074e-06,...","[0.11402207, 0.17918958, 0.10900098, 0.1399449...",23853,Q0005.npy
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3448,3448,"[blocked premature atrial contraction, 1st deg...",female,69.0,cpsc_extra,"[1st degree av block, st interval abnormal]","[0, 29]","[11, 0, 71, 56]",2,"[-2.5255713e-06, -4.6521704e-06, -1.8622202e-0...","[0.06468621, 0.15122691, 0.12547901, 0.0979289...",7522,Q3101.npy
3449,3449,"[st interval abnormal, bradycardia]",male,47.0,cpsc_extra,"[st interval abnormal, bradycardia]","[29, 7]","[56, 13]",0,"[0.00021216496, -0.00011917056, -0.0003313351,...","[0.08384262, 0.13519745, 0.054607492, 0.109042...",6000,Q3102.npy
3450,3450,[old myocardial infarction],male,67.0,cpsc_extra,[old myocardial infarction],[19],[36],1,"[-0.00026952417, 0.00013247445, 0.00040200053,...","[0.17938738, 0.2651329, 0.11857894, 0.21837437...",10500,Q3103.npy
3451,3451,"[1st degree av block, st interval abnormal]",male,75.0,cpsc_extra,"[1st degree av block, st interval abnormal]","[0, 29]","[0, 56]",8,"[0.00022979984, 5.1399493e-05, -0.00017839934,...","[0.09753762, 0.09577699, 0.06278253, 0.0912887...",5000,Q3104.npy
3452,3452,"[premature ventricular contractions, anterior ...",male,55.0,cpsc_extra,"[premature ventricular contractions, anterior ...","[21, 2, 16, 29]","[39, 3, 32, 56]",0,"[0.0003570603, -0.00039270573, 0.00025023695, ...","[0.13703145, 0.12621376, 0.11525303, 0.1183268...",8500,Q3105.npy

# Georgia

In [ ]:
georgia_data_path_root = DATASET_DIR / "georgia"
georgia_target_folder_root = TARGET_DIR / "georgia"

In [ ]:
df_georgia, _, _, _ = prepare_data_georgia(
    data_path=georgia_data_path_root,
    target_folder=georgia_target_folder_root
)

  0%|          | 0/10344 [00:00<?, ?it/s]

Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g5/E04603  data contains nans. Skipping.
Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g7/E06072  data contains nans. Skipping.
Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g7/E06909  data contains nans. Skipping.
Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g8/E07675  data contains nans. Skipping.
Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g8/E07941  data contains nans. Skipping.
Warning: /home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/georgia/g9/E08321  data contains nans. Skipping.
Creating CV folds: georgia

  0%|          | 0/67 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/19 [00:00<?, ?it/s]

  0%|          | 0/22 [00:00<?, ?it/s]

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

  0%|          | 0/27 [00:00<?, ?it/s]

  0%|          | 0/32 [00:00<?, ?it/s]

  0%|          | 0/34 [00:00<?, ?it/s]

  0%|          | 0/37 [00:00<?, ?it/s]

  0%|          | 0/42 [00:00<?, ?it/s]

  0%|          | 0/47 [00:00<?, ?it/s]

  0%|          | 0/58 [00:00<?, ?it/s]

  0%|          | 0/66 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/51 [00:00<?, ?it/s]

  0%|          | 0/65 [00:00<?, ?it/s]

  0%|          | 0/67 [00:00<?, ?it/s]

  0%|          | 0/77 [00:00<?, ?it/s]

  0%|          | 0/105 [00:00<?, ?it/s]

  0%|          | 0/106 [00:00<?, ?it/s]

  0%|          | 0/107 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/116 [00:00<?, ?it/s]

  0%|          | 0/159 [00:00<?, ?it/s]

  0%|          | 0/172 [00:00<?, ?it/s]

  0%|          | 0/239 [00:00<?, ?it/s]

  0%|          | 0/268 [00:00<?, ?it/s]

  0%|          | 0/282 [00:00<?, ?it/s]

  0%|          | 0/304 [00:00<?, ?it/s]

  0%|          | 0/221 [00:00<?, ?it/s]

  0%|          | 0/301 [00:00<?, ?it/s]

  0%|          | 0/327 [00:00<?, ?it/s]

  0%|          | 0/293 [00:00<?, ?it/s]

  0%|          | 0/330 [00:00<?, ?it/s]

  0%|          | 0/390 [00:00<?, ?it/s]

  0%|          | 0/380 [00:00<?, ?it/s]

  0%|          | 0/341 [00:00<?, ?it/s]

  0%|          | 0/302 [00:00<?, ?it/s]

  0%|          | 0/293 [00:00<?, ?it/s]

  0%|          | 0/382 [00:00<?, ?it/s]

  0%|          | 0/149 [00:00<?, ?it/s]

  0%|          | 0/285 [00:00<?, ?it/s]

  0%|          | 0/274 [00:00<?, ?it/s]

  0%|          | 0/378 [00:00<?, ?it/s]

  0%|          | 0/337 [00:00<?, ?it/s]

  0%|          | 0/342 [00:00<?, ?it/s]

  0%|          | 0/456 [00:00<?, ?it/s]

  0%|          | 0/1751 [00:00<?, ?it/s]

In [ ]:
reformat_as_memmap(
    df=df_georgia,
    target_filename=Path(georgia_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=georgia_target_folder_root
)

  0%|          | 0/10338 [00:00<?, ?it/s]

,data,label,sex,age,dataset,label_filtered,label_filtered_numeric,label_numeric,strat_fold,data_mean,data_std,data_length,data_original
0,0,[sinus rhythm],female,NaN,georgia,[sinus rhythm],[38],[47],0,"[0.059840772, 0.026323477, -0.033439033, -0.04...","[0.15747371, 0.064569406, 0.103534035, 0.10859...",5000,E00001.npy
1,1,[sinus rhythm],female,NaN,georgia,[sinus rhythm],[38],[47],5,"[0.05697511, 0.02905304, -0.027831353, -0.0430...","[0.15741223, 0.06417664, 0.10324846, 0.1085102...",5000,E00002.npy
2,2,[sinus rhythm],male,NaN,georgia,[sinus rhythm],[38],[47],7,"[0.032875817, 0.046173, 0.01326359, -0.0395596...","[0.10030736, 0.10994473, 0.051407278, 0.102015...",5000,E00003.npy
3,3,"[sinus bradycardia, lateral ischaemia, t wave ...",male,75.0,georgia,"[sinus bradycardia, lateral ischaemia, t wave ...","[37, 16, 45, 23]","[46, 22, 55, 29]",8,"[-0.016190594, -0.013312013, 0.0029739868, 0.0...","[0.06687792, 0.05467179, 0.08815632, 0.0422419...",5000,E00004.npy
4,4,"[right bundle branch block, atrial fibrillation]",male,83.0,georgia,"[right bundle branch block, atrial fibrillation]","[34, 4]","[41, 5]",3,"[-0.021357868, -0.020387452, 0.0010060022, 0.0...","[0.12534848, 0.11495075, 0.061032176, 0.116289...",5000,E00005.npy
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10333,10333,"[left axis deviation, sinus bradycardia]",male,41.0,georgia,"[left axis deviation, sinus bradycardia]","[20, 37]","[26, 46]",1,"[-0.010156186, -0.0136664715, -0.003620398, 0....","[0.10644678, 0.11999818, 0.07724641, 0.1066033...",5000,E08995.npy
10334,10334,"[left axis deviation, sinus bradycardia]",male,68.0,georgia,"[left axis deviation, sinus bradycardia]","[20, 37]","[26, 46]",1,"[-0.00065121485, 0.000100205645, 0.00063380005...","[0.11237143, 0.07791796, 0.079369575, 0.088138...",5000,E08996.npy
10335,10335,[t wave abnormal],female,38.0,georgia,[t wave abnormal],[45],[55],5,"[-0.012787841, 0.012997467, 0.025902664, -4.46...","[0.056473564, 0.17316328, 0.15651879, 0.102177...",5000,E08997.npy
10336,10336,[right bundle branch block],male,64.0,georgia,[right bundle branch block],[34],[41],2,"[-0.005731607, -0.005636807, -2.0210866e-05, 0...","[0.13691197, 0.16358052, 0.08092799, 0.1452844...",5000,E08998.npy
10337,10337,[nonspecific st t abnormality],female,72.0,georgia,[nonspecific st t abnormality],[26],[33],5,"[0.0017526048, -0.0063547106, -0.007955775, 0....","[0.16394289, 0.2098376, 0.07905073, 0.18408318...",5000,E08999.npy

# SPH

In [ ]:
sph_data_path_root = DATASET_DIR / "sph"
sph_target_folder_root = TARGET_DIR / "sph"

In [ ]:
df_sph, _, _, _ = prepare_data_sph(
    data_path=sph_data_path_root,
    target_folder=sph_target_folder_root
)

  0%|          | 0/25770 [00:00<?, ?it/s]

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/home/nvelingker/mkeoliya/kardia-lm/src/pipelines/ecg-fm-benchmarking/data/sph/records/A00001.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
reformat_as_memmap(
    df=df_sph,
    target_filename=Path(sph_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=sph_target_folder_root
)

# CODE-15%

In [ ]:
code15_data_path_root = DATASET_DIR / "code15"
code15_target_folder_root = TARGET_DIR / "code15"

In [ ]:
df_code15, _, _, _ = prepare_data_ribeiro_full(
    data_path=code15_data_path_root,
    code15=True,
    target_folder=code15_target_folder_root
)

Loading filenames...
Loading annotations...
In total 345797 records from more than 233771 patients before filtering.
Preparing labels for fold distribution...

  0%|          | 0/23 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/333 [00:00<?, ?it/s]

  0%|          | 0/422 [00:00<?, ?it/s]

  0%|          | 0/436 [00:00<?, ?it/s]

  0%|          | 0/393 [00:00<?, ?it/s]

  0%|          | 0/248 [00:00<?, ?it/s]

  0%|          | 0/335 [00:00<?, ?it/s]

  0%|          | 0/378 [00:00<?, ?it/s]

  0%|          | 0/917 [00:00<?, ?it/s]

  0%|          | 0/1807 [00:00<?, ?it/s]

  0%|          | 0/2112 [00:00<?, ?it/s]

  0%|          | 0/1431 [00:00<?, ?it/s]

  0%|          | 0/1351 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/442 [00:00<?, ?it/s]

  0%|          | 0/338 [00:00<?, ?it/s]

  0%|          | 0/255 [00:00<?, ?it/s]

  0%|          | 0/404 [00:00<?, ?it/s]

  0%|          | 0/439 [00:00<?, ?it/s]

  0%|          | 0/259 [00:00<?, ?it/s]

  0%|          | 0/279 [00:00<?, ?it/s]

  0%|          | 0/705 [00:00<?, ?it/s]

  0%|          | 0/2142 [00:00<?, ?it/s]

  0%|          | 0/2165 [00:00<?, ?it/s]

  0%|          | 0/1312 [00:00<?, ?it/s]

  0%|          | 0/1423 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/257 [00:00<?, ?it/s]

  0%|          | 0/272 [00:00<?, ?it/s]

  0%|          | 0/245 [00:00<?, ?it/s]

  0%|          | 0/216 [00:00<?, ?it/s]

  0%|          | 0/339 [00:00<?, ?it/s]

  0%|          | 0/242 [00:00<?, ?it/s]

  0%|          | 0/260 [00:00<?, ?it/s]

  0%|          | 0/757 [00:00<?, ?it/s]

  0%|          | 0/1826 [00:00<?, ?it/s]

  0%|          | 0/1465 [00:00<?, ?it/s]

  0%|          | 0/2364 [00:00<?, ?it/s]

  0%|          | 0/1920 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/151 [00:00<?, ?it/s]

  0%|          | 0/175 [00:00<?, ?it/s]

  0%|          | 0/177 [00:00<?, ?it/s]

  0%|          | 0/154 [00:00<?, ?it/s]

  0%|          | 0/212 [00:00<?, ?it/s]

  0%|          | 0/238 [00:00<?, ?it/s]

  0%|          | 0/343 [00:00<?, ?it/s]

  0%|          | 0/671 [00:00<?, ?it/s]

  0%|          | 0/2673 [00:00<?, ?it/s]

  0%|          | 0/2507 [00:00<?, ?it/s]

  0%|          | 0/1264 [00:00<?, ?it/s]

  0%|          | 0/1598 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/173 [00:00<?, ?it/s]

  0%|          | 0/151 [00:00<?, ?it/s]

  0%|          | 0/181 [00:00<?, ?it/s]

  0%|          | 0/176 [00:00<?, ?it/s]

  0%|          | 0/229 [00:00<?, ?it/s]

  0%|          | 0/238 [00:00<?, ?it/s]

  0%|          | 0/382 [00:00<?, ?it/s]

  0%|          | 0/683 [00:00<?, ?it/s]

  0%|          | 0/2598 [00:00<?, ?it/s]

  0%|          | 0/1980 [00:00<?, ?it/s]

  0%|          | 0/1587 [00:00<?, ?it/s]

  0%|          | 0/1785 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/149 [00:00<?, ?it/s]

  0%|          | 0/165 [00:00<?, ?it/s]

  0%|          | 0/189 [00:00<?, ?it/s]

  0%|          | 0/157 [00:00<?, ?it/s]

  0%|          | 0/205 [00:00<?, ?it/s]

  0%|          | 0/259 [00:00<?, ?it/s]

  0%|          | 0/561 [00:00<?, ?it/s]

  0%|          | 0/624 [00:00<?, ?it/s]

  0%|          | 0/2106 [00:00<?, ?it/s]

  0%|          | 0/2295 [00:00<?, ?it/s]

  0%|          | 0/1547 [00:00<?, ?it/s]

  0%|          | 0/1906 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/179 [00:00<?, ?it/s]

  0%|          | 0/140 [00:00<?, ?it/s]

  0%|          | 0/178 [00:00<?, ?it/s]

  0%|          | 0/155 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

  0%|          | 0/272 [00:00<?, ?it/s]

  0%|          | 0/575 [00:00<?, ?it/s]

  0%|          | 0/673 [00:00<?, ?it/s]

  0%|          | 0/2256 [00:00<?, ?it/s]

  0%|          | 0/2292 [00:00<?, ?it/s]

  0%|          | 0/1503 [00:00<?, ?it/s]

  0%|          | 0/1740 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

  0%|          | 0/187 [00:00<?, ?it/s]

  0%|          | 0/193 [00:00<?, ?it/s]

  0%|          | 0/197 [00:00<?, ?it/s]

  0%|          | 0/256 [00:00<?, ?it/s]

  0%|          | 0/577 [00:00<?, ?it/s]

  0%|          | 0/679 [00:00<?, ?it/s]

  0%|          | 0/2203 [00:00<?, ?it/s]

  0%|          | 0/2213 [00:00<?, ?it/s]

  0%|          | 0/1434 [00:00<?, ?it/s]

  0%|          | 0/1905 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/177 [00:00<?, ?it/s]

  0%|          | 0/149 [00:00<?, ?it/s]

  0%|          | 0/196 [00:00<?, ?it/s]

  0%|          | 0/175 [00:00<?, ?it/s]

  0%|          | 0/197 [00:00<?, ?it/s]

  0%|          | 0/248 [00:00<?, ?it/s]

  0%|          | 0/517 [00:00<?, ?it/s]

  0%|          | 0/672 [00:00<?, ?it/s]

  0%|          | 0/2316 [00:00<?, ?it/s]

  0%|          | 0/2435 [00:00<?, ?it/s]

  0%|          | 0/1167 [00:00<?, ?it/s]

  0%|          | 0/1914 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/182 [00:00<?, ?it/s]

  0%|          | 0/165 [00:00<?, ?it/s]

  0%|          | 0/166 [00:00<?, ?it/s]

  0%|          | 0/191 [00:00<?, ?it/s]

  0%|          | 0/249 [00:00<?, ?it/s]

  0%|          | 0/213 [00:00<?, ?it/s]

  0%|          | 0/375 [00:00<?, ?it/s]

  0%|          | 0/636 [00:00<?, ?it/s]

  0%|          | 0/2311 [00:00<?, ?it/s]

  0%|          | 0/1568 [00:00<?, ?it/s]

  0%|          | 0/1955 [00:00<?, ?it/s]

  0%|          | 0/2152 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/135 [00:00<?, ?it/s]

  0%|          | 0/175 [00:00<?, ?it/s]

  0%|          | 0/143 [00:00<?, ?it/s]

  0%|          | 0/154 [00:00<?, ?it/s]

  0%|          | 0/177 [00:00<?, ?it/s]

  0%|          | 0/269 [00:00<?, ?it/s]

  0%|          | 0/441 [00:00<?, ?it/s]

  0%|          | 0/527 [00:00<?, ?it/s]

  0%|          | 0/2080 [00:00<?, ?it/s]

  0%|          | 0/2292 [00:00<?, ?it/s]

  0%|          | 0/1778 [00:00<?, ?it/s]

  0%|          | 0/1992 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/154 [00:00<?, ?it/s]

  0%|          | 0/157 [00:00<?, ?it/s]

  0%|          | 0/174 [00:00<?, ?it/s]

  0%|          | 0/135 [00:00<?, ?it/s]

  0%|          | 0/190 [00:00<?, ?it/s]

  0%|          | 0/285 [00:00<?, ?it/s]

  0%|          | 0/453 [00:00<?, ?it/s]

  0%|          | 0/558 [00:00<?, ?it/s]

  0%|          | 0/2115 [00:00<?, ?it/s]

  0%|          | 0/2033 [00:00<?, ?it/s]

  0%|          | 0/1871 [00:00<?, ?it/s]

  0%|          | 0/2038 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/154 [00:00<?, ?it/s]

  0%|          | 0/158 [00:00<?, ?it/s]

  0%|          | 0/130 [00:00<?, ?it/s]

  0%|          | 0/128 [00:00<?, ?it/s]

  0%|          | 0/181 [00:00<?, ?it/s]

  0%|          | 0/249 [00:00<?, ?it/s]

  0%|          | 0/422 [00:00<?, ?it/s]

  0%|          | 0/598 [00:00<?, ?it/s]

  0%|          | 0/2328 [00:00<?, ?it/s]

  0%|          | 0/1941 [00:00<?, ?it/s]

  0%|          | 0/1891 [00:00<?, ?it/s]

  0%|          | 0/1983 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/193 [00:00<?, ?it/s]

  0%|          | 0/164 [00:00<?, ?it/s]

  0%|          | 0/178 [00:00<?, ?it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

  0%|          | 0/202 [00:00<?, ?it/s]

  0%|          | 0/248 [00:00<?, ?it/s]

  0%|          | 0/405 [00:00<?, ?it/s]

  0%|          | 0/654 [00:00<?, ?it/s]

  0%|          | 0/2607 [00:00<?, ?it/s]

  0%|          | 0/2397 [00:00<?, ?it/s]

  0%|          | 0/1504 [00:00<?, ?it/s]

  0%|          | 0/1442 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/197 [00:00<?, ?it/s]

  0%|          | 0/183 [00:00<?, ?it/s]

  0%|          | 0/184 [00:00<?, ?it/s]

  0%|          | 0/166 [00:00<?, ?it/s]

  0%|          | 0/250 [00:00<?, ?it/s]

  0%|          | 0/237 [00:00<?, ?it/s]

  0%|          | 0/413 [00:00<?, ?it/s]

  0%|          | 0/746 [00:00<?, ?it/s]

  0%|          | 0/2440 [00:00<?, ?it/s]

  0%|          | 0/2544 [00:00<?, ?it/s]

  0%|          | 0/1202 [00:00<?, ?it/s]

  0%|          | 0/1601 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/130 [00:00<?, ?it/s]

  0%|          | 0/162 [00:00<?, ?it/s]

  0%|          | 0/143 [00:00<?, ?it/s]

  0%|          | 0/146 [00:00<?, ?it/s]

  0%|          | 0/197 [00:00<?, ?it/s]

  0%|          | 0/247 [00:00<?, ?it/s]

  0%|          | 0/543 [00:00<?, ?it/s]

  0%|          | 0/634 [00:00<?, ?it/s]

  0%|          | 0/2209 [00:00<?, ?it/s]

  0%|          | 0/2152 [00:00<?, ?it/s]

  0%|          | 0/1672 [00:00<?, ?it/s]

  0%|          | 0/1928 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/209 [00:00<?, ?it/s]

  0%|          | 0/193 [00:00<?, ?it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

  0%|          | 0/187 [00:00<?, ?it/s]

  0%|          | 0/241 [00:00<?, ?it/s]

  0%|          | 0/272 [00:00<?, ?it/s]

  0%|          | 0/447 [00:00<?, ?it/s]

  0%|          | 0/642 [00:00<?, ?it/s]

  0%|          | 0/2389 [00:00<?, ?it/s]

  0%|          | 0/2447 [00:00<?, ?it/s]

  0%|          | 0/1264 [00:00<?, ?it/s]

  0%|          | 0/1703 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/158 [00:00<?, ?it/s]

  0%|          | 0/136 [00:00<?, ?it/s]

  0%|          | 0/137 [00:00<?, ?it/s]

  0%|          | 0/154 [00:00<?, ?it/s]

  0%|          | 0/217 [00:00<?, ?it/s]

  0%|          | 0/249 [00:00<?, ?it/s]

  0%|          | 0/361 [00:00<?, ?it/s]

  0%|          | 0/654 [00:00<?, ?it/s]

  0%|          | 0/2218 [00:00<?, ?it/s]

  0%|          | 0/1785 [00:00<?, ?it/s]

  0%|          | 0/1846 [00:00<?, ?it/s]

  0%|          | 0/2248 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/155 [00:00<?, ?it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

  0%|          | 0/159 [00:00<?, ?it/s]

  0%|          | 0/181 [00:00<?, ?it/s]

  0%|          | 0/211 [00:00<?, ?it/s]

  0%|          | 0/262 [00:00<?, ?it/s]

  0%|          | 0/407 [00:00<?, ?it/s]

  0%|          | 0/700 [00:00<?, ?it/s]

  0%|          | 0/2392 [00:00<?, ?it/s]

  0%|          | 0/1939 [00:00<?, ?it/s]

  0%|          | 0/1870 [00:00<?, ?it/s]

  0%|          | 0/1718 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/145 [00:00<?, ?it/s]

  0%|          | 0/152 [00:00<?, ?it/s]

  0%|          | 0/151 [00:00<?, ?it/s]

  0%|          | 0/132 [00:00<?, ?it/s]

  0%|          | 0/182 [00:00<?, ?it/s]

  0%|          | 0/278 [00:00<?, ?it/s]

  0%|          | 0/499 [00:00<?, ?it/s]

  0%|          | 0/552 [00:00<?, ?it/s]

  0%|          | 0/2145 [00:00<?, ?it/s]

  0%|          | 0/1982 [00:00<?, ?it/s]

  0%|          | 0/1847 [00:00<?, ?it/s]

  0%|          | 0/2098 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/196 [00:00<?, ?it/s]

  0%|          | 0/188 [00:00<?, ?it/s]

  0%|          | 0/166 [00:00<?, ?it/s]

  0%|          | 0/254 [00:00<?, ?it/s]

  0%|          | 0/198 [00:00<?, ?it/s]

  0%|          | 0/227 [00:00<?, ?it/s]

  0%|          | 0/400 [00:00<?, ?it/s]

  0%|          | 0/713 [00:00<?, ?it/s]

  0%|          | 0/2647 [00:00<?, ?it/s]

  0%|          | 0/2594 [00:00<?, ?it/s]

  0%|          | 0/1209 [00:00<?, ?it/s]

  0%|          | 0/1371 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/171 [00:00<?, ?it/s]

  0%|          | 0/161 [00:00<?, ?it/s]

  0%|          | 0/163 [00:00<?, ?it/s]

  0%|          | 0/161 [00:00<?, ?it/s]

  0%|          | 0/249 [00:00<?, ?it/s]

  0%|          | 0/222 [00:00<?, ?it/s]

  0%|          | 0/467 [00:00<?, ?it/s]

  0%|          | 0/644 [00:00<?, ?it/s]

  0%|          | 0/2751 [00:00<?, ?it/s]

  0%|          | 0/1626 [00:00<?, ?it/s]

  0%|          | 0/1662 [00:00<?, ?it/s]

  0%|          | 0/1886 [00:00<?, ?it/s]

  0%|          | 0/14 [00:00<?, ?it/s]

  0%|          | 0/211 [00:00<?, ?it/s]

  0%|          | 0/163 [00:00<?, ?it/s]

  0%|          | 0/207 [00:00<?, ?it/s]

  0%|          | 0/176 [00:00<?, ?it/s]

  0%|          | 0/249 [00:00<?, ?it/s]

  0%|          | 0/254 [00:00<?, ?it/s]

  0%|          | 0/418 [00:00<?, ?it/s]

  0%|          | 0/719 [00:00<?, ?it/s]

  0%|          | 0/2690 [00:00<?, ?it/s]

  0%|          | 0/2304 [00:00<?, ?it/s]

  0%|          | 0/1319 [00:00<?, ?it/s]

  0%|          | 0/1474 [00:00<?, ?it/s]

Fold distribution: strat_fold
 46    3465
 32    3464
 19    3463
 84    3462
 9     3462
       ...
 34    3453
 55    3453
 21    3452
 13    3452
-1       18
Name: count, Length: 101, dtype: int64
Reformating files...

  0%|          | 0/345797 [00:00<?, ?it/s]

Error processing id 214 filename exams_part0 empty waveform. Will be dropped.
Error processing id 2178 filename exams_part0 empty waveform. Will be dropped.
Error processing id 2396 filename exams_part0 empty waveform. Will be dropped.
Error processing id 2465 filename exams_part0 empty waveform. Will be dropped.
Error processing id 2519 filename exams_part0 empty waveform. Will be dropped.
Error processing id 3056 filename exams_part0 empty waveform. Will be dropped.
Error processing id 3123 filename exams_part0 empty waveform. Will be dropped.
Error processing id 3386 filename exams_part0 empty waveform. Will be dropped.
Error processing id 4120 filename exams_part0 empty waveform. Will be dropped.
Error processing id 4413 filename exams_part0 empty waveform. Will be dropped.
Error processing id 4553 filename exams_part0 empty waveform. Will be dropped.
Error processing id 6481 filename exams_part0 empty waveform. Will be dropped.
Error processing id 6592 filename exams_part0 empty waveform. Will be dropped.
Error processing id 6883 filename exams_part0 empty waveform. Will be dropped.
Error processing id 7693 filename exams_part0 empty waveform. Will be dropped.
Error processing id 9381 filename exams_part0 empty waveform. Will be dropped.
Error processing id 9779 filename exams_part0 empty waveform. Will be dropped.
Error processing id 9839 filename exams_part0 empty waveform. Will be dropped.
Error processing id 9970 filename exams_part0 empty waveform. Will be dropped.
Error processing id 10384 filename exams_part0 empty waveform. Will be dropped.
Error processing id 10472 filename exams_part0 empty waveform. Will be dropped.
Error processing id 10879 filename exams_part0 empty waveform. Will be dropped.
Error processing id 11488 filename exams_part0 empty waveform. Will be dropped.
Error processing id 11846 filename exams_part0 empty waveform. Will be dropped.
Error processing id 11928 filename exams_part0 empty waveform. Will be dropped.
Error processing id 12487 filename exams_part0 empty waveform. Will be dropped.
Error processing id 13436 filename exams_part0 empty waveform. Will be dropped.
Error processing id 14788 filename exams_part0 empty waveform. Will be dropped.
Error processing id 15304 filename exams_part0 empty waveform. Will be dropped.
Error processing id 15785 filename exams_part0 empty waveform. Will be dropped.
Error processing id 15851 filename exams_part0 empty waveform. Will be dropped.
Error processing id 15882 filename exams_part0 empty waveform. Will be dropped.
Error processing id 16630 filename exams_part0 empty waveform. Will be dropped.
Error processing id 16948 filename exams_part0 empty waveform. Will be dropped.
Error processing id 18433 filename exams_part0 empty waveform. Will be dropped.
Error processing id 18439 filename exams_part0 empty waveform. Will be dropped.
Error processing id 19717 filename exams_part0 empty waveform. Will be dropped.
Error processing id 19847 filename exams_part0 empty waveform. Will be dropped.
Error processing id 20000 filename exams_part0 empty waveform. Will be dropped.
Error processing id 20477 filename exams_part1 empty waveform. Will be dropped.
Error processing id 22070 filename exams_part1 empty waveform. Will be dropped.
Error processing id 22371 filename exams_part1 empty waveform. Will be dropped.
Error processing id 23355 filename exams_part1 empty waveform. Will be dropped.
Error processing id 23711 filename exams_part1 empty waveform. Will be dropped.
Error processing id 23951 filename exams_part1 empty waveform. Will be dropped.
Error processing id 23953 filename exams_part1 empty waveform. Will be dropped.
Error processing id 24261 filename exams_part1 empty waveform. Will be dropped.
Error processing id 24663 filename exams_part1 empty waveform. Will be dropped.
Error processing id 25047 filename exams_part1 empty waveform. Will be dropped.
Error processing id 25512 filename exams_part1 empty waveform. Will be dropped.
Error processing id 25700 filename exams_part1 empty waveform. Will be dropped.
Error processing id 25982 filename exams_part1 empty waveform. Will be dropped.
Error processing id 26577 filename exams_part1 empty waveform. Will be dropped.
Error processing id 26740 filename exams_part1 empty waveform. Will be dropped.
Error processing id 26769 filename exams_part1 empty waveform. Will be dropped.
Error processing id 27188 filename exams_part1 empty waveform. Will be dropped.
Error processing id 27671 filename exams_part1 empty waveform. Will be dropped.
Error processing id 27676 filename exams_part1 empty waveform. Will be dropped.
Error processing id 28113 filename exams_part1 empty waveform. Will be dropped.
Error processing id 28507 filename exams_part1 empty waveform. Will be dropped.
Error processing id 28626 filename exams_part1 empty waveform. Will be dropped.
Error processing id 28883 filename exams_part1 empty waveform. Will be dropped.
Error processing id 29124 filename exams_part1 empty waveform. Will be dropped.
Error processing id 29168 filename exams_part1 empty waveform. Will be dropped.
Error processing id 29281 filename exams_part1 empty waveform. Will be dropped.
Error processing id 29307 filename exams_part1 empty waveform. Will be dropped.
Error processing id 30703 filename exams_part1 empty waveform. Will be dropped.
Error processing id 30874 filename exams_part1 empty waveform. Will be dropped.
Error processing id 30928 filename exams_part1 empty waveform. Will be dropped.
Error processing id 31383 filename exams_part1 empty waveform. Will be dropped.
Error processing id 31757 filename exams_part1 empty waveform. Will be dropped.
Error processing id 32047 filename exams_part1 empty waveform. Will be dropped.
Error processing id 32171 filename exams_part1 empty waveform. Will be dropped.
Error processing id 33749 filename exams_part1 empty waveform. Will be dropped.
Error processing id 34316 filename exams_part1 empty waveform. Will be dropped.
Error processing id 34355 filename exams_part1 empty waveform. Will be dropped.
Error processing id 34970 filename exams_part1 empty waveform. Will be dropped.
Error processing id 35581 filename exams_part1 empty waveform. Will be dropped.
Error processing id 35810 filename exams_part1 empty waveform. Will be dropped.
Error processing id 35813 filename exams_part1 empty waveform. Will be dropped.
Error processing id 35923 filename exams_part1 empty waveform. Will be dropped.
Error processing id 36696 filename exams_part1 empty waveform. Will be dropped.
Error processing id 37446 filename exams_part1 empty waveform. Will be dropped.
Error processing id 37920 filename exams_part1 empty waveform. Will be dropped.
Error processing id 38235 filename exams_part1 empty waveform. Will be dropped.
Error processing id 38569 filename exams_part1 empty waveform. Will be dropped.
Error processing id 39316 filename exams_part1 empty waveform. Will be dropped.
Error processing id 39566 filename exams_part1 empty waveform. Will be dropped.
Error processing id 39796 filename exams_part1 empty waveform. Will be dropped.
Error processing id 39987 filename exams_part1 empty waveform. Will be dropped.
Error processing id 40001 filename exams_part1 empty waveform. Will be dropped.
Error processing id 40480 filename exams_part2 empty waveform. Will be dropped.
Error processing id 40732 filename exams_part2 empty waveform. Will be dropped.
Error processing id 41550 filename exams_part2 empty waveform. Will be dropped.
Error processing id 42004 filename exams_part2 empty waveform. Will be dropped.
Error processing id 42244 filename exams_part2 empty waveform. Will be dropped.
Error processing id 42802 filename exams_part2 empty waveform. Will be dropped.
Error processing id 43203 filename exams_part2 empty waveform. Will be dropped.
Error processing id 43452 filename exams_part2 empty waveform. Will be dropped.
Error processing id 43467 filename exams_part2 empty waveform. Will be dropped.
Error processing id 43671 filename exams_part2 empty waveform. Will be dropped.
Error processing id 44216 filename exams_part2 empty waveform. Will be dropped.
Error processing id 44385 filename exams_part2 empty waveform. Will be dropped.
Error processing id 44435 filename exams_part2 empty waveform. Will be dropped.
Error processing id 45315 filename exams_part2 empty waveform. Will be dropped.
Error processing id 45530 filename exams_part2 empty waveform. Will be dropped.
Error processing id 45854 filename exams_part2 empty waveform. Will be dropped.
Error processing id 46026 filename exams_part2 empty waveform. Will be dropped.
Error processing id 46164 filename exams_part2 empty waveform. Will be dropped.
Error processing id 46515 filename exams_part2 empty waveform. Will be dropped.
Error processing id 46602 filename exams_part2 empty waveform. Will be dropped.
Error processing id 47579 filename exams_part2 empty waveform. Will be dropped.
Error processing id 47956 filename exams_part2 empty waveform. Will be dropped.
Error processing id 48310 filename exams_part2 empty waveform. Will be dropped.
Error processing id 48812 filename exams_part2 empty waveform. Will be dropped.
Error processing id 49059 filename exams_part2 empty waveform. Will be dropped.
Error processing id 49178 filename exams_part2 empty waveform. Will be dropped.
Error processing id 50246 filename exams_part2 empty waveform. Will be dropped.
Error processing id 50362 filename exams_part2 empty waveform. Will be dropped.
Error processing id 50630 filename exams_part2 empty waveform. Will be dropped.
Error processing id 50654 filename exams_part2 empty waveform. Will be dropped.
Error processing id 50724 filename exams_part2 empty waveform. Will be dropped.
Error processing id 51336 filename exams_part2 empty waveform. Will be dropped.
Error processing id 52312 filename exams_part2 empty waveform. Will be dropped.
Error processing id 52585 filename exams_part2 empty waveform. Will be dropped.
Error processing id 53794 filename exams_part2 empty waveform. Will be dropped.
Error processing id 54598 filename exams_part2 empty waveform. Will be dropped.
Error processing id 54833 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55396 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55421 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55458 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55473 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55590 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55675 filename exams_part2 empty waveform. Will be dropped.
Error processing id 55852 filename exams_part2 empty waveform. Will be dropped.
Error processing id 56484 filename exams_part2 empty waveform. Will be dropped.
Error processing id 56539 filename exams_part2 empty waveform. Will be dropped.
Error processing id 56981 filename exams_part2 empty waveform. Will be dropped.
Error processing id 57384 filename exams_part2 empty waveform. Will be dropped.
Error processing id 58313 filename exams_part2 empty waveform. Will be dropped.
Error processing id 59768 filename exams_part2 empty waveform. Will be dropped.
Error processing id 59938 filename exams_part2 empty waveform. Will be dropped.
Error processing id 59941 filename exams_part2 empty waveform. Will be dropped.
Error processing id 60002 filename exams_part2 empty waveform. Will be dropped.
Error processing id 60598 filename exams_part3 empty waveform. Will be dropped.
Error processing id 60930 filename exams_part3 empty waveform. Will be dropped.
Error processing id 61079 filename exams_part3 empty waveform. Will be dropped.
Error processing id 61545 filename exams_part3 empty waveform. Will be dropped.
Error processing id 63680 filename exams_part3 empty waveform. Will be dropped.
Error processing id 64803 filename exams_part3 empty waveform. Will be dropped.
Error processing id 64941 filename exams_part3 empty waveform. Will be dropped.
Error processing id 65080 filename exams_part3 empty waveform. Will be dropped.
Error processing id 65320 filename exams_part3 empty waveform. Will be dropped.
Error processing id 65527 filename exams_part3 empty waveform. Will be dropped.
Error processing id 65802 filename exams_part3 empty waveform. Will be dropped.
Error processing id 66314 filename exams_part3 empty waveform. Will be dropped.
Error processing id 66473 filename exams_part3 empty waveform. Will be dropped.
Error processing id 66623 filename exams_part3 empty waveform. Will be dropped.
Error processing id 67657 filename exams_part3 empty waveform. Will be dropped.
Error processing id 67671 filename exams_part3 empty waveform. Will be dropped.
Error processing id 67937 filename exams_part3 empty waveform. Will be dropped.
Error processing id 68854 filename exams_part3 empty waveform. Will be dropped.
Error processing id 69026 filename exams_part3 empty waveform. Will be dropped.
Error processing id 69105 filename exams_part3 empty waveform. Will be dropped.
Error processing id 72905 filename exams_part3 empty waveform. Will be dropped.
Error processing id 72952 filename exams_part3 empty waveform. Will be dropped.
Error processing id 73462 filename exams_part3 empty waveform. Will be dropped.
Error processing id 73485 filename exams_part3 empty waveform. Will be dropped.
Error processing id 74604 filename exams_part3 empty waveform. Will be dropped.
Error processing id 74767 filename exams_part3 empty waveform. Will be dropped.
Error processing id 75385 filename exams_part3 empty waveform. Will be dropped.
Error processing id 76188 filename exams_part3 empty waveform. Will be dropped.
Error processing id 76712 filename exams_part3 empty waveform. Will be dropped.
Error processing id 76788 filename exams_part3 empty waveform. Will be dropped.
Error processing id 77373 filename exams_part3 empty waveform. Will be dropped.
Error processing id 80003 filename exams_part3 empty waveform. Will be dropped.
Error processing id 81962 filename exams_part4 empty waveform. Will be dropped.
Error processing id 82441 filename exams_part4 empty waveform. Will be dropped.
Error processing id 83315 filename exams_part4 empty waveform. Will be dropped.
Error processing id 83803 filename exams_part4 empty waveform. Will be dropped.
Error processing id 83846 filename exams_part4 empty waveform. Will be dropped.
Error processing id 83986 filename exams_part4 empty waveform. Will be dropped.
Error processing id 84398 filename exams_part4 empty waveform. Will be dropped.
Error processing id 84941 filename exams_part4 empty waveform. Will be dropped.
Error processing id 85022 filename exams_part4 empty waveform. Will be dropped.
Error processing id 85251 filename exams_part4 empty waveform. Will be dropped.
Error processing id 85295 filename exams_part4 empty waveform. Will be dropped.
Error processing id 85417 filename exams_part4 empty waveform. Will be dropped.
Error processing id 85497 filename exams_part4 empty waveform. Will be dropped.
Error processing id 86415 filename exams_part4 empty waveform. Will be dropped.
Error processing id 87249 filename exams_part4 empty waveform. Will be dropped.
Error processing id 87601 filename exams_part4 empty waveform. Will be dropped.
Error processing id 89452 filename exams_part4 empty waveform. Will be dropped.
Error processing id 89800 filename exams_part4 empty waveform. Will be dropped.
Error processing id 90335 filename exams_part4 empty waveform. Will be dropped.
Error processing id 90756 filename exams_part4 empty waveform. Will be dropped.
Error processing id 91476 filename exams_part4 empty waveform. Will be dropped.
Error processing id 92093 filename exams_part4 empty waveform. Will be dropped.
Error processing id 93169 filename exams_part4 empty waveform. Will be dropped.
Error processing id 93603 filename exams_part4 empty waveform. Will be dropped.
Error processing id 93966 filename exams_part4 empty waveform. Will be dropped.
Error processing id 93982 filename exams_part4 empty waveform. Will be dropped.
Error processing id 94403 filename exams_part4 empty waveform. Will be dropped.
Error processing id 94470 filename exams_part4 empty waveform. Will be dropped.
Error processing id 95176 filename exams_part4 empty waveform. Will be dropped.
Error processing id 97473 filename exams_part4 empty waveform. Will be dropped.
Error processing id 97542 filename exams_part4 empty waveform. Will be dropped.
Error processing id 99799 filename exams_part4 empty waveform. Will be dropped.
Error processing id 100004 filename exams_part4 empty waveform. Will be dropped.
Error processing id 100794 filename exams_part5 empty waveform. Will be dropped.
Error processing id 100834 filename exams_part5 empty waveform. Will be dropped.
Error processing id 100847 filename exams_part5 empty waveform. Will be dropped.
Error processing id 100912 filename exams_part5 empty waveform. Will be dropped.
Error processing id 101987 filename exams_part5 empty waveform. Will be dropped.
Error processing id 102159 filename exams_part5 empty waveform. Will be dropped.
Error processing id 102829 filename exams_part5 empty waveform. Will be dropped.
Error processing id 103223 filename exams_part5 empty waveform. Will be dropped.
Error processing id 104474 filename exams_part5 empty waveform. Will be dropped.
Error processing id 104661 filename exams_part5 empty waveform. Will be dropped.
Error processing id 105428 filename exams_part5 empty waveform. Will be dropped.
Error processing id 106195 filename exams_part5 empty waveform. Will be dropped.
Error processing id 107022 filename exams_part5 empty waveform. Will be dropped.
Error processing id 107063 filename exams_part5 empty waveform. Will be dropped.
Error processing id 107324 filename exams_part5 empty waveform. Will be dropped.
Error processing id 108157 filename exams_part5 empty waveform. Will be dropped.
Error processing id 109127 filename exams_part5 empty waveform. Will be dropped.
Error processing id 109639 filename exams_part5 empty waveform. Will be dropped.
Error processing id 109909 filename exams_part5 empty waveform. Will be dropped.
Error processing id 110547 filename exams_part5 empty waveform. Will be dropped.
Error processing id 111322 filename exams_part5 empty waveform. Will be dropped.
Error processing id 111419 filename exams_part5 empty waveform. Will be dropped.
Error processing id 111459 filename exams_part5 empty waveform. Will be dropped.
Error processing id 111992 filename exams_part5 empty waveform. Will be dropped.
Error processing id 112968 filename exams_part5 empty waveform. Will be dropped.
Error processing id 113564 filename exams_part5 empty waveform. Will be dropped.
Error processing id 114533 filename exams_part5 empty waveform. Will be dropped.
Error processing id 114641 filename exams_part5 empty waveform. Will be dropped.
Error processing id 116291 filename exams_part5 empty waveform. Will be dropped.
Error processing id 116472 filename exams_part5 empty waveform. Will be dropped.
Error processing id 117015 filename exams_part5 empty waveform. Will be dropped.
Error processing id 117056 filename exams_part5 empty waveform. Will be dropped.
Error processing id 117556 filename exams_part5 empty waveform. Will be dropped.
Error processing id 119693 filename exams_part5 empty waveform. Will be dropped.
Error processing id 120005 filename exams_part5 empty waveform. Will be dropped.
Error processing id 120037 filename exams_part6 empty waveform. Will be dropped.
Error processing id 120689 filename exams_part6 empty waveform. Will be dropped.
Error processing id 121279 filename exams_part6 empty waveform. Will be dropped.
Error processing id 121685 filename exams_part6 empty waveform. Will be dropped.
Error processing id 121834 filename exams_part6 empty waveform. Will be dropped.

In [ ]:
reformat_as_memmap(
    df=df_code15,
    target_filename=Path(code15_target_folder_root)/"memmap.npy",
    fs=400,
    channel_itos=CHANNEL_ITOS,
    data_folder=code15_target_folder_root
)

NameError: name 'reformat_as_memmap' is not defined

# MIMIC

In [4]:
mimic_data_path_root = DATASET_DIR / "mimic"
mimic_target_folder_root = TARGET_DIR / "mimic"

In [5]:
df_mimic, _, _, _ = prepare_mimicecg(
    data_path=mimic_data_path_root,
    target_folder=mimic_target_folder_root
)

KeyboardInterrupt:

In [ ]:
reformat_as_memmap(
    df=df_mimic,
    target_filename=Path(mimic_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=mimic_target_folder_root
)

In [ ]:
!python3 mimic_preprocessing.py

# EchoNext

In [ ]:
echonext_data_path_root = DATASET_DIR / "echonext"
echonext_target_folder_root = TARGET_DIR / "echonext"

In [ ]:
df_echonext, _, _, _ = prepare_data_echonext(
    data_path=echonext_data_path_root,
    target_folder=echonext_target_folder_root
)

In [ ]:
reformat_as_memmap(
    df=df_echonext,
    target_filename=Path(echonext_target_folder_root)/"memmap.npy",
    fs=250,
    channel_itos=CHANNEL_ITOS,
    data_folder=echonext_target_folder_root
)

# ZZU pECG

In [ ]:
zzu_pecg_data_path_root = DATASET_DIR / "zzu_pecg"
zzu_pecg_target_folder_root = TARGET_DIR / "zzu_pecg"

In [ ]:
df_zzu_pecg, _, _, _ = prepare_data_zzu_pecg(
    data_path=zzu_pecg_data_path_root,
    target_folder=zzu_pecg_target_folder_root
)

In [ ]:
reformat_as_memmap(
    df=df_zzu_pecg,
    target_filename=Path(zzu_pecg_target_folder_root)/"memmap.npy",
    fs=500,
    channel_itos=CHANNEL_ITOS,
    data_folder=zzu_pecg_target_folder_root
)

# HEEDB

In [ ]:
heedb_data_path_root = DATASET_DIR / "heedb"
heedb_target_folder_root = TARGET_DIR / "heedb"

In [ ]:
partitions = ['S0001-1987', 'S0001-1988', 'S0001-1994', 'S0001-2006', 'S0001-2007', 'S0001-2011', 'S0001-2013', 'S0001-2015', 'S0001-2016', 'S0001-2017', 'S0001-2018', 'S0001-2019', 'S0001-2020', 'S0001-2021', 'S0002-1993', 'S0002-1997', 'S0002-1998', 'S0002-2000', 'S0002-2003', 'S0002-2004', 'S0002-2008', 'S0002-2009', 'S0002-2013', 'S0002-2015', 'S0002-2016', 'S0002-2018', 'S0002-2020', 'S0002-2022', 'S0003-1990', 'S0003-1994', 'S0003-2009', 'S0003-2010', 'S0003-2013', 'S0004-2019']

for partition in partitions:
    df_heedb, _, _, _ = prepare_heedb(
        data_path=heedb_data_path_root,
        target_folder=heedb_target_folder_root,
        partition=partition
    )

    reformat_as_memmap(
        df=df_heedb,
        target_filename=Path(heedb_target_folder_root)/ f"{partition}" /"memmap.npy",
        fs=240,
        channel_itos=CHANNEL_ITOS,
        data_folder=Path(heedb_target_folder_root) / f"{partition}"
    )